server:
  port: 9001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac?characterEncoding=utf-8
    username: root
    password: root

mybatis:
  type-aliases-package: com.bgs.buba_auth_service.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #驼峰写法

logging:
  level:
    com:buba:buba_auth_service: debug

rsa:
  key:
    pubKeyFile: D:\key\pri_key
    priKeyFile: D:\key\public_key